import type { TransactionAction } from "../schema/types.js";
import type { SyncId } from "../sync/sync-id.js";

/**
 * State of a transaction in the sync pipeline
 */
export type TransactionState =
  // In local outbox, not yet sent
  | "queued"
  // Sent to server, awaiting confirmation
  | "sent"
  // Server confirmed, waiting for sync ID
  | "awaitingSync"
  // Fully synced
  | "completed"
  // Failed permanently
  | "failed";

/**
 * A single transaction representing a local mutation
 */
export interface Transaction {
  /** Unique ID generated by the client for idempotency */
  clientTxId: string;
  /** Client instance identifier */
  clientId: string;
  /** Name of the model being mutated */
  modelName: string;
  /** ID of the model instance */
  modelId: string;
  /** Type of mutation */
  action: TransactionAction;
  /** New/changed data for the mutation */
  payload: Record<string, unknown>;
  /** Original data before mutation (for rollback) */
  original?: Record<string, unknown>;
  /** Current state in the sync pipeline */
  state: TransactionState;
  /** Timestamp when transaction was created */
  createdAt: number;
  /** Number of retry attempts */
  retryCount: number;
  /** Last error message if failed */
  lastError?: string;
  /** Sync ID required before the transaction is considered complete */
  syncIdNeededForCompletion?: SyncId;
  /** Batch index used for grouping transactions */
  batchIndex?: number;
}

/**
 * A batch of transactions to send to the server
 */
export interface TransactionBatch {
  /** Unique ID for the batch */
  batchId: string;
  /** Transactions in the batch */
  transactions: Transaction[];
  /** Timestamp when batch was created */
  createdAt: number;
}

/**
 * Result of a single transaction from the server
 */
export interface TransactionResult {
  /** Client transaction ID */
  clientTxId: string;
  /** Whether the transaction succeeded */
  success: boolean;
  /** Assigned sync ID if successful */
  syncId?: SyncId;
  /** Error message if failed */
  error?: string;
  /** Error code if failed */
  errorCode?: string;
}

/**
 * Result of a batch mutation from the server
 */
export interface MutateResult {
  /** Whether the overall batch succeeded */
  success: boolean;
  /** Highest sync ID after mutations */
  lastSyncId: SyncId;
  /** Results for each transaction */
  results: TransactionResult[];
}

/**
 * Options for creating a transaction
 */
export interface CreateTransactionOptions {
  clientId: string;
  modelName: string;
  modelId: string;
  action: TransactionAction;
  payload: Record<string, unknown>;
  original?: Record<string, unknown>;
}
