name = "stratasync-docs-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[observability]
enabled = true

[vars]
DOCS_URL = "docs.stratasync.dev"
CUSTOM_URL = "stratasync.dev"
LANDING_URL = "landing.stratasync.dev"
